// Set up needed tools
export const SET_ETHERS = "SET_ETHERS";
export const SET_UP = "SET_UP";
export const SET_UP_3BOX = "SET_UP_3BOX";
export const SET_UP_ONBOARD = "SET_UP_ONBOARD";
export const SET_UP_CONTRACTS = "SET_UP_CONTRACTS";
// User unique token actions
export const CREATE_USER_THREAD = "CREATE_USER_THREAD";
export const LOAD_USER_THREAD = "LOAD_USER_THREAD";
export const GET_USER_TOKEN = "GET_USER_TOKEN";

export const LOAD_AUTHORS_CONTENT = "LOAD_AUTHORS_CONTENT";
export const CREATE_USER = "CREATE_USER";
export const CREATE_POST = "CREATE_POST";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_AUTHOR_POSTS = "GET_ALL_AUTHOR_POSTS";
export const MAKE_TIP = "MAKE_TIP";
export const SET_USER_NAME = "SET_USER_NAME";
export const LOAD_USER_NAMES_FROM_BOX = "LOAD_USER_NAMES_FROM_BOX";